const mfo = {
  "id": "new",
  "type": "mfo",
  "main": {
    "title": "Новый партнер",
    "logo": "img/kredito24-logo.png",
    "money": "",
    "term": "",
    "minRate": "",
    "link": "",
    "firstLoan": "",
    "overpayment": ""
  },
  "details": {
    "minSumm": "",
    "maxSumm": "",
    "minPercent": "",
    "maxPercent": "",
    "minTerm": "",
    "maxTerm": "",
    "appProcessTime": "",
    "getMoneyTime": "",
    "penalty": "",
    "incomeProof": "",
    "regionRegistr": "",
    "identification": "",
    "age": "",
    "obtainingMethods": "",
    "repaymentOptions": "",
    "creditHistory": "",
    "schedule": "",
    "personalArea": "",
    "application": "",
    "creditHistoryImprovement": "",
    "smsInfo": ""
  },
  "categories": {
    "badCreditHistory": false,
    "online": false,
    "fast": false,
    "instantApprove": false,
    "urgently": false,
    "express": false,
    "DaN": false,
    "inCash": false,
    "instant": false,
    "accordingPassport": false,
    "toPaycheck": false,
    "longTerm": false,
    "withoutFailure": false,
    "withoutGuarantors": false,
    "forStudents": false,
    "forPensioners": false,
    "noInterest": false,
    "from18Years": false,
    "unemployed": false,
    "withoutPassport": false,
    "noCreditHistory": false
  },
  "filters": {
    "special_offers": [false, false],
    "summ": [false, false, false, false, false, false, false],
    "review_time": [false, false, false, false],
    "get_money_time": [false, false, false, false],
    "income_proof": [false, false],
    "credit_history": [false, false],
    "get_ways": [false, false, false, false, false, false, false],
    "repayment_options": [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    "age": [false, false, false, false, false],
    "mob_app": [false, false]
  },
  "sortBy": {
    "summ": 0,
    "term": 0,
    "rate": 0
  }
}

const cards = {
  "id": "new",
  "type": "cards",
  "main": {
    "title": "Новый партнер",
    "logo": "img/alfa-100-dnei.png",
    "limit": "",
    "percent": "",
    "cashback": "",
    "link": "",
    "firstLoan": ""
  },
  "details": {
    "paySystem": "",
    "cardType": "",
    "validity": "",
    "minLimit": "",
    "maxLimit": "",
    "interestRate": "",
    "maintenanceСost": "",
    "gracePeriod": "",
    "commission": "",
    "cashback": "",
    "minPayment": "",
    "considerationTime": "",
    "delivery": "",
    "deliveryTime": "",
    "incomeProof": "",
    "age": "",
    "regionRegistr": "",
    "chipAvailability": "",
    "contactlessPayment": "",
    "secure3D": "",
    "supplyDepartment": "",
    "application": "",
    "internetBank": ""
  },
  "categories": {
    "alfaBank": false,
    "tinkoff": false,
    "bestCards": false,
    "mostProfitable": false,
    "dayOfTreatment": false,
    "withoutInterest": false,
    "urgent": false,
    "withoutFailure": false,
    "withoutReferences": false,
    "deliveryPlace": false,
    "withoutAnnualService": false,
    "withoutIncomeProof": false,
    "withoutCreditHistory": false,
    "forPensioners": false,
    "forStudents": false,
    "unemployed": false,
    "interestFreePeriod": false,
    "cashback": false,
    "instant": false,
    "forCashWithdrawals": false,
    "virtual": false,
    "applePay": false,
    "samsungPay": false,
    "in5Minutes": false,
    "in15Minutes": false,
    "in30Minutes": false,
    "visa": false,
    "masterCard": false,
    "mir": false
  },
  "filters": {
    "payment_system": [false, false, false],
    "validity": [false, false, false, false],
    "limits": [false, false, false, false, false],
    "grace_period": [false, false, false, false],
    "cashback": [false, false],
    "consideration_time": [false, false, false, false, false],
    "card_delivery": [false, false],
    "time_delivery": [false, false, false],
    "income_proof": [false, false],
    "age": [false, false, false, false, false],
    "chip_availability": [false, false],
    "secure_3d": [false, false],
    "mob_app": [false, false]
  },
  "sortBy": {
    "limit": 0,
    "rate": 0,
    "cashback": 0
  }
}

export default {mfo, cards}
